version: '3.3'

services:
  web:
    container_name: web
    build: .
    volumes:
      - web_data:/usr/share/website/data
    networks:
      main:
    ports:
      - "8001:8001"
    restart: always


networks:
  main:

volumes:
  web_data: